config/routes.rb
Rails.application.routes.draw do
  resources :clients

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
# frozen_string_literal: true

# Provides details of a client including address.
class Client < ApplicationRecord
  has_many :sessions, dependent: :destroy
  has_many :session_charges, dependent: :destroy

  # There must be at least one session charge setup for the client
  validates :session_charges, presence: true
  validate :session_charges_must_not_overlap

  # Add a default session_charges record if none exists.
  after_initialize do |client|
    client.session_charges.build(from: Time.zone.today, hourly_charge_rate: 60) if client.session_charges.empty?
  end

  # @return Money
  def current_rate
    self.current_session_charge&.hourly_charge_rate
  end

  # Sets the current rate for sessions if different from current rate as held in database.  Updates the
  # current rate in the database to be up to yesterday, and creates a new session_charges record starting
  # today with an open ended charge period.
  # @return [Money]
  def current_rate=(rate)
    active_session_charge = self.current_session_charge

    if active_session_charge.nil?
      # No record exists yet, so create a new one.
      _build_active_session_charge(rate)
    elsif active_session_charge.hourly_charge_rate != rate
      # Something has changed, so ...
      if active_session_charge.persisted?
        # If this is a persisted (ie existing) session_charge, then amend date period and add the new record.
        active_session_charge.update!(to: Date.today - 1.day)
        _build_active_session_charge(rate)
      else
        # If not yet persisted, then update existing unsaved record.
        active_session_charge.hourly_charge_rate = rate
      end
    end
    rate
  end

  def _build_active_session_charge(rate)
    self.session_charges << SessionCharge.new(from: Date.today, to: nil, hourly_charge_rate: rate)
  end

  # Returns the current session_charge record.
  def current_session_charge
    if self.id
      self.session_charges.find_by(to: nil)
    else
      self.session_charges.find { |session_charge| session_charge.to.nil? }
    end
  end

  def session_charges_must_not_overlap
    overlap_error = SessionCharge.overlap?(self.session_charges)

    if overlap_error
      self.errors.add(:session_charges, "Session charge to #{overlap_error.to} overlaps with its successor")
    end
  end
end

app/models/session.rb
# frozen_string_literal: true

# Describes a single session for a client with the therapist.
class Session < ApplicationRecord
  belongs_to :client

  monetize :hourly_charge_pence
end

app/models/session_charge.rb
# frozen_string_literal: true

# Describes the standard session charge that is applied to charges within a defined period.  If the `to` field
# is *nil*, then the charge period is open ended.
class SessionCharge < ApplicationRecord
  belongs_to :client

  monetize :hourly_charge_rate_pence

  # Checks if for the provided client_id any session charge entries' date ranges overlap.
  # @param [ActiveResult] session_charges
  # @return [SessionCharge|false]
  def self.overlap?(session_charges)
    return false if session_charges.length <= 1

    overlapping_pair = session_charges.each_cons(2).find { |previous, following| previous.to >= following.from }
    overlapping_pair&.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[show edit update destroy]

  # GET /clients
  def index
    @clients = Client.all

    respond_to do |format|
      format.html { render inertia: 'clients/index' }
      format.json { render :index }
    end
  end

  # GET /clients/1
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client, notice: "Client was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /clients/1
  def update
    if @client.update(client_params)
      redirect_to @client, notice: "Client was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, notice: "Client was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :address1, :address2, :town, :postcode)
    end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    render inertia: 'Application'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address1, style: "display: block" %>
    <%= form.text_field :address1 %>
  </div>

  <div>
    <%= form.label :address2, style: "display: block" %>
    <%= form.text_field :address2 %>
  </div>

  <div>
    <%= form.label :town, style: "display: block" %>
    <%= form.text_field :town %>
  </div>

  <div>
    <%= form.label :postcode, style: "display: block" %>
    <%= form.text_field :postcode %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= content_tag :div, "", id: "clients-show" %>
<%= vite_typescript_tag 'clients'  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invoicing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= vite_stylesheet_tag "application.scss" %>

    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
    <!--
      If using a TypeScript entrypoint file:
        vite_typescript_tag 'application'

      If using a .jsx or .tsx entrypoint, add the extension:
        vite_javascript_tag 'application.jsx'

      Visit the guide for more information: https://vite-ruby.netlify.app/guide/rails
    -->

  </head>

  <body>
    <%= yield %>
  </body>
</html>